config/routes.rb
D2::Application.routes.draw do  
  resources :current_day_routes

  resources :current_day_pickups

  resources :archives

  resources :pickups

  resources :customers

  resources :routes

  resources :drivers

   root :to => 'Customers#index'

end

app/models/pickup.rb
class Pickup < ActiveRecord::Base
    validates :PickupTableID, :presence => true
    validates :PickupTableID, :uniqueness => true 
    validates :RouteName, :DefaultRouteID, :PickupDate, :CustomerID, 
              :DriverName, :RouteName, :CustomerName, :Comment, 
               :Dispatched, 
              :DispatchTime, :Notes , :presence => true
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  # GET /pickups
  # GET /pickups.json
  def index
    @pickups = Pickup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pickups }
    end
  end

  # GET /pickups/1
  # GET /pickups/1.json
  def show
    @pickup = Pickup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pickup }
    end
  end

  # GET /pickups/new
  # GET /pickups/new.json
  def new
    @pickup = Pickup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pickup }
    end
  end

  # GET /pickups/1/edit
  def edit
    @pickup = Pickup.find(params[:id])
  end

  # POST /pickups
  # POST /pickups.json
  def create
    @pickup = Pickup.new(params[:pickup])

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to @pickup, notice: 'Pickup was successfully created.' }
        format.json { render json: @pickup, status: :created, location: @pickup }
      else
        format.html { render action: "new" }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pickups/1
  # PUT /pickups/1.json
  def update
    @pickup = Pickup.find(params[:id])

    respond_to do |format|
      if @pickup.update_attributes(params[:pickup])
        format.html { redirect_to @pickup, notice: 'Pickup was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.json
  def destroy
    @pickup = Pickup.find(params[:id])
    @pickup.destroy

    respond_to do |format|
      format.html { redirect_to pickups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/views/pickups/_form.html.erb
<%= form_for(@pickup) do |f| %>
  <% if @pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
      <% @pickup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :PickupTableID %><br />
    <%= f.number_field :PickupTableID %>
  </div>
  <div class="field">
    <%= f.label :DefaultRouteID %><br />
    <%= f.text_field :DefaultRouteID %>
  </div>
  <div class="field">
    <%= f.label :PickupDate %><br />
    <%= f.datetime_select :PickupDate %>
  </div>
  <div class="field">
    <%= f.label :CustomerID %><br />
    <%= f.text_field :CustomerID %>
  </div>
  <div class="field">
    <%= f.label :DriverName %><br />
    <%= f.text_field :DriverName %>
  </div>
  <div class="field">
    <%= f.label :RouteName %><br />
    <%= f.text_field :RouteName %>
  </div>
  <div class="field">
    <%= f.label :CustomerName %><br />
    <%= f.text_field :CustomerName %>
  </div>
  <div class="field">
    <%= f.label :Comment %><br />
    <%= f.text_field :Comment %>
  </div>
  <div class="field">
    <%= f.label :Monday %><br />
    <%= f.check_box :Monday %>
  </div>
  <div class="field">
    <%= f.label :Tuesday %><br />
    <%= f.check_box :Tuesday %>
  </div>
  <div class="field">
    <%= f.label :Wednesday %><br />
    <%= f.check_box :Wednesday %>
  </div>
  <div class="field">
    <%= f.label :Thursday %><br />
    <%= f.check_box :Thursday %>
  </div>
  <div class="field">
    <%= f.label :Friday %><br />
    <%= f.check_box :Friday %>
  </div>
  <div class="field">
    <%= f.label :Dispatched %><br />
    <%= f.check_box :Dispatched %>
  </div>
  <div class="field">
    <%= f.label :DispatchTime %><br />
    <%= f.datetime_select :DispatchTime %>
  </div>
  <div class="field">
    <%= f.label :Notes %><br />
    <%= f.text_field :Notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pickups/edit.html.erb
<h1>Editing pickup</h1>

<%= render 'form' %>

<%= link_to 'Show', @pickup %> |
<%= link_to 'Back', pickups_path %>

app/views/pickups/index.html.erb
<h1>Listing pickups</h1>

<table>
  <tr>
    <th>Pickuptableid</th>
    <th>Defaultrouteid</th>
    <th>Pickupdate</th>
    <th>Customerid</th>
    <th>Drivername</th>
    <th>Routename</th>
    <th>Customername</th>
    <th>Comment</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Dispatched</th>
    <th>Dispatchtime</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pickups.each do |pickup| %>
  <tr>
    <td><%= pickup.PickupTableID %></td>
    <td><%= pickup.DefaultRouteID %></td>
    <td><%= pickup.PickupDate %></td>
    <td><%= pickup.CustomerID %></td>
    <td><%= pickup.DriverName %></td>
    <td><%= pickup.RouteName %></td>
    <td><%= pickup.CustomerName %></td>
    <td><%= pickup.Comment %></td>
    <td><%= pickup.Monday %></td>
    <td><%= pickup.Tuesday %></td>
    <td><%= pickup.Wednesday %></td>
    <td><%= pickup.Thursday %></td>
    <td><%= pickup.Friday %></td>
    <td><%= pickup.Dispatched %></td>
    <td><%= pickup.DispatchTime %></td>
    <td><%= pickup.Notes %></td>
    <td><%= link_to 'Show', pickup %></td>
    <td><%= link_to 'Edit', edit_pickup_path(pickup) %></td>
    <td><%= link_to 'Destroy', pickup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pickup', new_pickup_path %>

app/views/pickups/new.html.erb
<h1>New pickup</h1>

<%= render 'form' %>

<%= link_to 'Back', pickups_path %>

app/views/pickups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pickuptableid:</b>
  <%= @pickup.PickupTableID %>
</p>

<p>
  <b>Defaultrouteid:</b>
  <%= @pickup.DefaultRouteID %>
</p>

<p>
  <b>Pickupdate:</b>
  <%= @pickup.PickupDate %>
</p>

<p>
  <b>Customerid:</b>
  <%= @pickup.CustomerID %>
</p>

<p>
  <b>Drivername:</b>
  <%= @pickup.DriverName %>
</p>

<p>
  <b>Routename:</b>
  <%= @pickup.RouteName %>
</p>

<p>
  <b>Customername:</b>
  <%= @pickup.CustomerName %>
</p>

<p>
  <b>Comment:</b>
  <%= @pickup.Comment %>
</p>

<p>
  <b>Monday:</b>
  <%= @pickup.Monday %>
</p>

<p>
  <b>Tuesday:</b>
  <%= @pickup.Tuesday %>
</p>

<p>
  <b>Wednesday:</b>
  <%= @pickup.Wednesday %>
</p>

<p>
  <b>Thursday:</b>
  <%= @pickup.Thursday %>
</p>

<p>
  <b>Friday:</b>
  <%= @pickup.Friday %>
</p>

<p>
  <b>Dispatched:</b>
  <%= @pickup.Dispatched %>
</p>

<p>
  <b>Dispatchtime:</b>
  <%= @pickup.DispatchTime %>
</p>

<p>
  <b>Notes:</b>
  <%= @pickup.Notes %>
</p>


<%= link_to 'Edit', edit_pickup_path(@pickup) %> |
<%= link_to 'Back', pickups_path %>