config/routes.rb
D2::Application.routes.draw do  
  resources :current_day_routes

  resources :current_day_pickups

  resources :archives

  resources :pickups

  resources :customers

  resources :routes

  resources :drivers

   root :to => 'Customers#index'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
    validates :DriverID, :presence => true
    validates :DriverID, :uniqueness => true 
    validates :FirstName, :LastName, :presence => true
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drivers }
    end
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.json
  def new
    @driver = Driver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(params[:driver])

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render json: @driver, status: :created, location: @driver }
      else
        format.html { render action: "new" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.json
  def update
    @driver = Driver.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DriverID %><br />
    <%= f.text_field :DriverID %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br />
    <%= f.text_field :FirstName %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br />
    <%= f.text_field :LastName %>
  </div>
  <div class="field">
    <%= f.label :MiddleInitial %><br />
    <%= f.text_field :MiddleInitial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<table>
  <tr>
    <th>Driverid</th>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Middleinitial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.DriverID %></td>
    <td><%= driver.FirstName %></td>
    <td><%= driver.LastName %></td>
    <td><%= driver.MiddleInitial %></td>
    <td><%= link_to 'Show', driver %></td>
    <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
    <td><%= link_to 'Destroy', driver, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Driverid:</b>
  <%= @driver.DriverID %>
</p>

<p>
  <b>Firstname:</b>
  <%= @driver.FirstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @driver.LastName %>
</p>

<p>
  <b>Middleinitial:</b>
  <%= @driver.MiddleInitial %>
</p>


<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>