config/routes.rb
D2::Application.routes.draw do  
  resources :current_day_routes

  resources :current_day_pickups

  resources :archives

  resources :pickups

  resources :customers

  resources :routes

  resources :drivers

   root :to => 'Customers#index'

end

app/models/current_day_pickup.rb
class CurrentDayPickup < ActiveRecord::Base

    validates :CurrentDayPickupID, :presence => true
    validates :CurrentDayPickupID, :uniqueness => true 
    validates :CDPDefaultRouteID, :CDPPreviousRouteID, 
#:CDPPickupDate,
    :CDPCustomerID, :CDPDriverName, :CDPDriverMessage,
    :CDPRouteName, :CDPCustomerName, :CDPComment,
    :CDPDispatched, :CDPDispatchTime, :CDPNotes,
    :CDPStation, 
#:CDPChecked, :CDPDeleted,
    :PostedCount, :Terminal,
    :presence => true
    
end
  

app/controllers/current_day_pickups_controller.rb
class CurrentDayPickupsController < ApplicationController
  # GET /current_day_pickups
  # GET /current_day_pickups.json
  def index
    @current_day_pickups = CurrentDayPickup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @current_day_pickups }
    end
  end

  # GET /current_day_pickups/1
  # GET /current_day_pickups/1.json
  def show
    @current_day_pickup = CurrentDayPickup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @current_day_pickup }
    end
  end

  # GET /current_day_pickups/new
  # GET /current_day_pickups/new.json
  def new
    @current_day_pickup = CurrentDayPickup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @current_day_pickup }
    end
  end

  # GET /current_day_pickups/1/edit
  def edit
    @current_day_pickup = CurrentDayPickup.find(params[:id])
  end

  # POST /current_day_pickups
  # POST /current_day_pickups.json
  def create
    @current_day_pickup = CurrentDayPickup.new(params[:current_day_pickup])

    respond_to do |format|
      if @current_day_pickup.save
        format.html { redirect_to @current_day_pickup, notice: 'Current day pickup was successfully created.' }
        format.json { render json: @current_day_pickup, status: :created, location: @current_day_pickup }
      else
        format.html { render action: "new" }
        format.json { render json: @current_day_pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /current_day_pickups/1
  # PUT /current_day_pickups/1.json
  def update
    @current_day_pickup = CurrentDayPickup.find(params[:id])

    respond_to do |format|
      if @current_day_pickup.update_attributes(params[:current_day_pickup])
        format.html { redirect_to @current_day_pickup, notice: 'Current day pickup was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @current_day_pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_day_pickups/1
  # DELETE /current_day_pickups/1.json
  def destroy
    @current_day_pickup = CurrentDayPickup.find(params[:id])
    @current_day_pickup.destroy

    respond_to do |format|
      format.html { redirect_to current_day_pickups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/current_day_pickups_helper.rb
module CurrentDayPickupsHelper
end

app/views/current_day_pickups/_form.html.erb
<%= form_for(@current_day_pickup) do |f| %>
  <% if @current_day_pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_day_pickup.errors.count, "error") %> prohibited this current_day_pickup from being saved:</h2>

      <ul>
      <% @current_day_pickup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CurrentDayPickupID %><br />
    <%= f.number_field :CurrentDayPickupID %>
  </div>
  <div class="field">
    <%= f.label :CDPDefaultRouteID %><br />
    <%= f.text_field :CDPDefaultRouteID %>
  </div>
  <div class="field">
    <%= f.label :CDPPreviousRouteID %><br />
    <%= f.text_field :CDPPreviousRouteID %>
  </div>
  <div class="field">
    <%= f.label :CDPPickupDate %><br />
    <%= f.datetime_select :CDPPickupDate %>
  </div>
  <div class="field">
    <%= f.label :CDPCustomerID %><br />
    <%= f.text_field :CDPCustomerID %>
  </div>
  <div class="field">
    <%= f.label :CDPDriverName %><br />
    <%= f.text_field :CDPDriverName %>
  </div>
  <div class="field">
    <%= f.label :CDPDriverMessage %><br />
    <%= f.text_field :CDPDriverMessage %>
  </div>
  <div class="field">
    <%= f.label :CDPRouteName %><br />
    <%= f.text_field :CDPRouteName %>
  </div>
  <div class="field">
    <%= f.label :CDPCustomerName %><br />
    <%= f.text_field :CDPCustomerName %>
  </div>
  <div class="field">
    <%= f.label :CDPComment %><br />
    <%= f.text_field :CDPComment %>
  </div>
  <div class="field">
    <%= f.label :CDPDispatched %><br />
    <%= f.check_box :CDPDispatched %>
  </div>
  <div class="field">
    <%= f.label :CDPDispatchTime %><br />
    <%= f.datetime_select :CDPDispatchTime %>
  </div>
  <div class="field">
    <%= f.label :CDPNotes %><br />
    <%= f.text_field :CDPNotes %>
  </div>
  <div class="field">
    <%= f.label :CDPStation %><br />
    <%= f.text_field :CDPStation %>
  </div>
  <div class="field">
    <%= f.label :CDPChecked %><br />
    <%= f.check_box :CDPChecked %>
  </div>
  <div class="field">
    <%= f.label :CDPDeleted %><br />
    <%= f.check_box :CDPDeleted %>
  </div>
  <div class="field">
    <%= f.label :PostedCount %><br />
    <%= f.number_field :PostedCount %>
  </div>
  <div class="field">
    <%= f.label :Terminal %><br />
    <%= f.text_field :Terminal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/current_day_pickups/edit.html.erb
<h1>Editing current_day_pickup</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_day_pickup %> |
<%= link_to 'Back', current_day_pickups_path %>

app/views/current_day_pickups/index.html.erb
<h1>Listing current_day_pickups</h1>

<table>
  <tr>
    <th>Currentdaypickupid</th>
    <th>Cdpdefaultrouteid</th>
    <th>Cdppreviousrouteid</th>
    <th>Cdppickupdate</th>
    <th>Cdpcustomerid</th>
    <th>Cdpdrivername</th>
    <th>Cdpdrivermessage</th>
    <th>Cdproutename</th>
    <th>Cdpcustomername</th>
    <th>Cdpcomment</th>
    <th>Cdpdispatched</th>
    <th>Cdpdispatchtime</th>
    <th>Cdpnotes</th>
    <th>Cdpstation</th>
    <th>Cdpchecked</th>
    <th>Cdpdeleted</th>
    <th>Postedcount</th>
    <th>Terminal</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @current_day_pickups.each do |current_day_pickup| %>
  <tr>
    <td><%= current_day_pickup.CurrentDayPickupID %></td>
    <td><%= current_day_pickup.CDPDefaultRouteID %></td>
    <td><%= current_day_pickup.CDPPreviousRouteID %></td>
    <td><%= current_day_pickup.CDPPickupDate %></td>
    <td><%= current_day_pickup.CDPCustomerID %></td>
    <td><%= current_day_pickup.CDPDriverName %></td>
    <td><%= current_day_pickup.CDPDriverMessage %></td>
    <td><%= current_day_pickup.CDPRouteName %></td>
    <td><%= current_day_pickup.CDPCustomerName %></td>
    <td><%= current_day_pickup.CDPComment %></td>
    <td><%= current_day_pickup.CDPDispatched %></td>
    <td><%= current_day_pickup.CDPDispatchTime %></td>
    <td><%= current_day_pickup.CDPNotes %></td>
    <td><%= current_day_pickup.CDPStation %></td>
    <td><%= current_day_pickup.CDPChecked %></td>
    <td><%= current_day_pickup.CDPDeleted %></td>
    <td><%= current_day_pickup.PostedCount %></td>
    <td><%= current_day_pickup.Terminal %></td>
    <td><%= link_to 'Show', current_day_pickup %></td>
    <td><%= link_to 'Edit', edit_current_day_pickup_path(current_day_pickup) %></td>
    <td><%= link_to 'Destroy', current_day_pickup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Current day pickup', new_current_day_pickup_path %>

app/views/current_day_pickups/new.html.erb
<h1>New current_day_pickup</h1>

<%= render 'form' %>

<%= link_to 'Back', current_day_pickups_path %>

app/views/current_day_pickups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Currentdaypickupid:</b>
  <%= @current_day_pickup.CurrentDayPickupID %>
</p>

<p>
  <b>Cdpdefaultrouteid:</b>
  <%= @current_day_pickup.CDPDefaultRouteID %>
</p>

<p>
  <b>Cdppreviousrouteid:</b>
  <%= @current_day_pickup.CDPPreviousRouteID %>
</p>

<p>
  <b>Cdppickupdate:</b>
  <%= @current_day_pickup.CDPPickupDate %>
</p>

<p>
  <b>Cdpcustomerid:</b>
  <%= @current_day_pickup.CDPCustomerID %>
</p>

<p>
  <b>Cdpdrivername:</b>
  <%= @current_day_pickup.CDPDriverName %>
</p>

<p>
  <b>Cdpdrivermessage:</b>
  <%= @current_day_pickup.CDPDriverMessage %>
</p>

<p>
  <b>Cdproutename:</b>
  <%= @current_day_pickup.CDPRouteName %>
</p>

<p>
  <b>Cdpcustomername:</b>
  <%= @current_day_pickup.CDPCustomerName %>
</p>

<p>
  <b>Cdpcomment:</b>
  <%= @current_day_pickup.CDPComment %>
</p>

<p>
  <b>Cdpdispatched:</b>
  <%= @current_day_pickup.CDPDispatched %>
</p>

<p>
  <b>Cdpdispatchtime:</b>
  <%= @current_day_pickup.CDPDispatchTime %>
</p>

<p>
  <b>Cdpnotes:</b>
  <%= @current_day_pickup.CDPNotes %>
</p>

<p>
  <b>Cdpstation:</b>
  <%= @current_day_pickup.CDPStation %>
</p>

<p>
  <b>Cdpchecked:</b>
  <%= @current_day_pickup.CDPChecked %>
</p>

<p>
  <b>Cdpdeleted:</b>
  <%= @current_day_pickup.CDPDeleted %>
</p>

<p>
  <b>Postedcount:</b>
  <%= @current_day_pickup.PostedCount %>
</p>

<p>
  <b>Terminal:</b>
  <%= @current_day_pickup.Terminal %>
</p>


<%= link_to 'Edit', edit_current_day_pickup_path(@current_day_pickup) %> |
<%= link_to 'Back', current_day_pickups_path %>